# Generate the warp positioning CSS block for the 14 user markers.
import json

mk = json.load(open("exported_map_art/warp_markers.json"))
FRAME_W_EM = 25.3125
FRAME_H_EM = 16.875

lines = [
    "/* ==== CUSTOM WORLD MAP: 14 warp markers (user-annotated) ====",
    "    Positions = marker% of the 25.3125em x 16.875em map frame,",
    "    centered on a 2em icon. Icons all use mapicons col 0 (the",
    "    same 3-state normal/hover/active sprite). Generated by",
    "    scripts/_gen_warp_css.py from warp_markers.json — regenerate",
    "    after re-annotating. ==== */",
]
for m in mk["markers"]:
    i = m["id"]
    x = m["x"] / 270 * FRAME_W_EM - 1.0  # center a 2em icon
    y = m["y"] / 180 * FRAME_H_EM - 1.0
    lines.append(
        f"#hud-hub #warp{i} {{ top: {y:.4f}em; left: {x:.4f}em; }}"
    )
css = "\n".join(lines)
with open("exported_map_art/warp_positions.css", "w") as f:
    f.write(css)
print(css)
